version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: msg-backend
    expose:
      - "8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
