CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    photo BYTEA,
    unique_id VARCHAR(255) NOT NULL UNIQUE,
    about TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
